# Generated by Django 4.1.5 on 2023-02-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
            preserve_default=False,
        ),
    ]
