# Generated by Django 4.1.5 on 2023-02-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Feature', 'Feature'), ('New', 'New')], max_length=10, verbose_name='flag'),
        ),
    ]
