# Generated by Django 4.1.5 on 2023-05-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_flag"),
        ("orders", "0006_alter_cartdetail_cart_alter_cartdetail_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdetail",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_detail",
                to="orders.cart",
                verbose_name="cart_detail",
            ),
        ),
        migrations.AlterField(
            model_name="cartdetail",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_product",
                to="product.product",
                verbose_name="cart_product",
            ),
        ),
    ]
